export interface Ticket {
  id: string;
  title: string;
  description: string;
  status: string;
  priority: string;
  source: string | null;
  category_id: string | null;
  category_name: string | null;
  subcategory_id: string | null;
  group_id: string | null;
  assigned_to: string | null;
  assigned_to_name: string | null;
  customer_name: string | null;
  customer_email: string | null;
  customer_phone: string | null;
  company_name: string | null;
  company_id: string | null;
  contact_id: string | null;
  contact_name: string | null;
  contact_first_name: string | null;
  contact_last_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  contact_position: string | null;
  due_date: string | null;
  resolution_time: number | null;
  created_at: string;
  created_by: string | null;
  created_by_name: string | null;
  updated_at: string | null;
  updated_by: string | null;
  is_deleted: boolean;
  parent_company_id: string | null;
  sla_breach: boolean | null;
  comments?: Comment[];
  tags?: string[];
}

export interface Comment {
  id: string;
  ticket_id: string;
  content: string;
  is_internal: boolean;
  attachments?: FileAttachment[];
  created_at: string;
  created_by: string;
  created_by_name: string;
  updated_at: string | null;
  updated_by: string | null;
}

export interface TicketComment {
  id?: string;
  ticket_id: string;
  content: string;
  is_internal: boolean;
  attachments?: FileAttachment[];
  created_at: string;
  created_by: string;
  created_by_name: string;
}

export interface FileAttachment {
  id: string;
  name: string;
  size: number;
  type: string;
  url: string;
  uploaded_at: string;
  uploaded_by: string;
}

export interface Company {
  id: string;
  name: string;
  parent_company_id: string | null;
  // Add other company properties as needed
}

export interface Contact {
  id: string;
  first_name: string;
  last_name: string;
  name: string; // This is generated by concatenating first_name and last_name in the database
  email: string | null;
  phone: string | null;
  position: string | null;
  company_id: string | null;
  company_name: string | null;
  // Add other contact properties as needed
}
